language: go

go:
    - 1.7.1

install:
  - go get github.com/masterzen/winrm
  - go get github.com/mitchellh/packer
  - cd $GOPATH/src/github.com/mitchellh/packer
  - git checkout v0.8.6
  - go get ./...

