language: go

go:
    - 1.7.1

install:
  - mkdir -p $GOPATH/src/github.com/masterzen
  - git clone https://github.com/masterzen/winrm $GOPATH/src/github.com/masterzen/winrm
  - cd $GOPATH/src/github.com/masterzen/winrm
  - git checkout 54ea5d01478cfc2afccec1504bd0dfcd8c260cfa
  - go get github.com/mitchellh/packer
  - cd $GOPATH/src/github.com/mitchellh/packer
  - git checkout v0.8.6
  - go get -v -d ./... || true
