language: go

go:
    - 1.7.1

install:
  - go get github.com/masterzen/winrm
  - cd $GOPATH/src/github.com/masterzen/winrm
  - git checkout 54ea5d01478cfc2afccec1504bd0dfcd8c260cfa
  - go get github.com/mitchellh/packer
  - cd $GOPATH/src/github.com/mitchellh/packer
  - git checkout v0.8.6
  - make dev
